by Suman Kumar Bera
skbera.iitkgp21@gmail.com
for Tutorial of AMLBS on 04/09/23

Problem taken from: https://www.javatpoint.com/pytorch-backpropagation-process-in-deep-neural-network

In [2]:
## NN

# Import the necessary libraries
import numpy as np

# define the class
class NN:

  def __init__(self, input_layer_size = 2, hidden_layer_size = 2, output_layer_size = 2, lr = 0.5, epoches = 1000):  # define the constructor
    self.input_layer_size = input_layer_size
    self.hidden_layer_size = hidden_layer_size
    self.output_layer_size = output_layer_size
    self.lr = lr
    self.number_of_epoches = epoches

    #initialize the weights
    #1. by random numbers
    # self.W1 = np.random.randn(self.input_layer_size, self.hidden_layer_size)
    # self.W2 = np.random.randn(self.hidden_layer_size, self.output_layer_size)
    # print(f'W1 = {self.W1}')
    # print(f'W2 = {self.W2}')

    #2. with zeros
    # self.W1 = np.zeros((self.input_layer_size, self.hidden_layer_size))
    # self.W2 = np.zeros((self.hidden_layer_size, self.output_layer_size))
    # print(f'W1 = {self.W1}')
    # print(f'W2 = {self.W2}')

    #3. specific numbers
    self.W1 = np.array([[0.15, 0.25], [0.20, 0.30]])  # ([[w1, w3], [w2, w4]])
    self.W2 = np.array([[0.40, 0.50], [0.45, 0.55]])
    # print(f'W1 = \n{self.W1}')
    # print(f'W2 = \n{self.W2}')

    # bias
    self.b1 = 0.35
    self.b2 = 0.60

  # define the activation function
  def activation(self, x):
    return (1 / (1 + np.exp(-x)))

  # forward pass
  def forward(self, X):
    self.hidden = self.activation(np.dot(X, self.W1) + self.b1)  # H = activation(X*W1 + b)
    self.output = self.activation(np.dot(self.hidden, self.W2) + self.b2)  # OP = activation(H*W2 + b)

    # print(f'H = {self.hidden}')
    # print(f'OP = {self.output}')
    return self.output

  # back propagation
  def back_prop(self, X, y):
    output = self.forward(X)
    error = np.sum((y - output)**2/2)
    # print(f'Error = {error}')
    self.W2 -= self.lr * (np.dot(self.hidden.T, np.multiply(-(y - output), output * (1 - output)))) # W2 = W2 - alpha * (H * ((y-OP) * (OP * (OP - 1))))
    print(f'New W2 Weights: {self.W2}')

    # self.W1 -= ?

  # training; update the weights for the given number of epoches
  # def train(self, X, y):
  #   for _ in range(self.number_of_epoches):
  #     self.back_prop(X, y)


# create an instance of the class
model = NN()
# define the input and output
X = np.array([[0.05, 0.10]]) #input
y = np.array([[0.01, 0.99]]) #output
model.forward(X)
# model.back_prop(X, y)

array([[0.75136507, 0.77292847]])

In [ ]:
# difference between np.dot and np.multiply

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

print(f'np.dot = \n', np.dot(a, b))
print(f'np.multiply = \n', np.multiply(a, b))

np.dot = 
 [[19 22]
 [43 50]]
np.multiply = 
 [[ 5 12]
 [21 32]]


In [ ]:
# Dataset
import pandas as pd
import numpy as np


df = pd.read_csv('/content/drive/MyDrive/Tutorial_04 09 23/housing.csv')
df

RM  LSTAT  PTRATIO      MEDV
0    6.575   4.98     15.3  504000.0
1    6.421   9.14     17.8  453600.0
2    7.185   4.03     17.8  728700.0
3    6.998   2.94     18.7  701400.0
4    7.147   5.33     18.7  760200.0
..     ...    ...      ...       ...
484  6.593   9.67     21.0  470400.0
485  6.120   9.08     21.0  432600.0
486  6.976   5.64     21.0  501900.0
487  6.794   6.48     21.0  462000.0
488  6.030   7.88     21.0  249900.0

[489 rows x 4 columns]

In [ ]:
X_data = df.drop(columns=['MEDV'])
y_data = df['MEDV']
X_data = X_data.to_numpy()
y_data = y_data.to_numpy()
X_data = (X_data-np.min(X_data))/(np.max(X_data)-np.min(X_data))
y_data = (y_data-np.min(y_data))/(np.max(y_data)-np.min(y_data))
print(X_data.shape)
print(y_data.shape)

(489, 3)
(489,)
